# === Identificación del proyecto ===
sonar.projectKey=paz_y_salvos_crud
sonar.projectName=paz_y_salvos_crud
sonar.projectVersion=1.0
sonar.language=go

# === Directorios del código fuente ===
sonar.sources=./
sonar.sources.inclusions=**/**.go

# === Exclusiones (archivos o carpetas que no se analizan) ===
sonar.exclusions=swagger/**,routers/**,database/**

# === Configuración de pruebas ===
# sonar.tests=./
# sonar.test.inclusions=**/*.spec.*,**/*.test.*

#----- Default SonarQube server
sonar.host.url=https://sonarqube.portaloas.udistrital.edu.co/

# === Configuración de red y proxy ===
# Deshabilita la verificación DTD para evitar problemas de proxy
sonar.scanner.force.deprecatedKey.enableXXE=false

# === Lenguaje y codificación ===
sonar.sourceEncoding=UTF-8